### PR TITLE
Swift: Check If Two String Arrays are Equivalent

### PR DESCRIPTION
**Pull request by GabrielaBezerra**
It was cool to solve this one using functional programming. It is a skill I'm still practicing and learning along the codes I make.

### CODE REVIEW

**Comment by All3yp** [comment]
Please, create a readme with the question. Like this: 

Captura de Tela 2022-10-25 às 12 53 41

**Comment by GabrielaBezerra** [comment]
Sorry, I totally forgot it. Please take a look at the one I've just created

**Comment by All3yp** [comment]
Sorry, but your readme are still incorrect, you need anexed the link about question, and not put strong tag

**Comment by GabrielaBezerra** [comment]
Altered it to look just like the leet code website

**Review by All3yp — APPROVED** [review]
Well done, thanks for u contribution o/ 🎉

**Pull request merged**
